=== Wabtey/ArtManipulation/Part2/public_html/Q7-DTD.dtd
<!ELEMENT body(documentation | personne)*>

<!ELEMENT documentation(#PCDATA | lien)*>
<!ELEMENT texte(#PCDATA)>
<!ELEMENT lien(#PCDATA)> -- same as texte -->

<!ELEMENT personne(id, nom, site-web?, reputation?, capital?, type?, nationalite)>
<!ATTLIST personne
	date CDATA #REQUIRED
>

<!ELEMENT id EMPTY>
<!ATTLIST id 
	num ID #REQUIRED
>
<!ELEMENT nom(#PCDATA)>

<!ELEMENT site-web(lien)>
<!ELEMENT reputation(EMPTY)>
<!ATTLIST reputation 
	num ID #REQUIRED
>
<!ELEMENT capital(EMPTY)>
<!ATTLIST capital 
	num ID #REQUIRED
>
<!ELEMENT type(#PCDATA)>
<!ELEMENT nationalite(#PCDATA)>

=== Wabtey/ArtManipulation/P2/public_html/Q8-XML.xml
<?xml version="1.0" encoding="iso-8859-1" ?>
<?xml-stylesheet href="Q10-SML.css" type="text/css"?>

<!DOCTYPE petit-texte SYSTEM "Q7-DTD.dtd">
<body>
    <personne>
        <id num='1'/>
    	<nom>Nelson Van Amerungen</nom>
    	<site-web>
            <lien>
            https://Un-personne-ultra-sympa.fabinie/Monkey
            </lien>
        </site-web>
        <reputation num='5417'/>
        <capital num='2'/>
    
    </personne>

    <documentation>
        Le gitHub du projet :
        <lien>https://github.com/Wabtey/art-manipulation</lien>
    </documentation>
</body>
